#if defined _store_included
 #endinput
#endif
#define _store_included

#include <store/store-core>
#include <store/store-backend>
#include <store/store-inventory>
#include <store/store-shop>
#include <store/store-loadout>
#include <store/store-logging>

//External Includes
#include <multicolors>

#define STORE_AUTHORS "Alongub, Keith Warren(Drixevel), Arrow768"
#define STORE_URL "https://github.com/alongubkin/store"
#define STORE_VERSION "1.2.4b"

#define STORE_PREFIX "\x04[Store] \x01"